export default {"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", alias4=container.escapeExpression, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<!DOCTYPE html>\n<html lang=\"en-US\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <meta name=\"viewport\" content=\"width=device-width\" />\n    <link href=\"./test.css\" rel=\"stylesheet\" />\n\n    <div class=\"container\">\n      <div class=\"background-image\">\n      </div>  \n      <div class=\"profile-grid\">\n      \n        <div class=\"basic-info\">\n          <h1 class=\"bold text-6xl text-left text-white uppercase\">"
    + alias4(((helper = (helper = lookupProperty(helpers,"name") || (depth0 != null ? lookupProperty(depth0,"name") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"name","hash":{},"data":data,"loc":{"start":{"line":14,"column":67},"end":{"line":14,"column":75}}}) : helper)))
    + "</h1>\n          <h4 class=\"bold mb-4 mt-4 text-4xl text-left text-white uppercase\">"
    + alias4(((helper = (helper = lookupProperty(helpers,"title") || (depth0 != null ? lookupProperty(depth0,"title") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"title","hash":{},"data":data,"loc":{"start":{"line":15,"column":77},"end":{"line":15,"column":86}}}) : helper)))
    + "</h4>\n          <div class=\"education-section\">\n            <p class=\"mt-4 text-2xl tracking-widest\">WPI</p>\n            <p class=\"text-2xl tracking-widest\">B.S Computer Science</p>\n          </div>\n        </div>\n  \n        <img class=\"profile-image\" src=\"./assets/headshot.png\"/>\n        \n        <div class=\"fun-fact\">\n          <h4 class=\"bold pt-4 text-5xl text-left text-white fun-fact-title\">Fun Fact</h1>\n          <p class=\"mt-2 text-left text-xl text-white font-semibold\">Likes long walks on the beach</h4>\n        </div>\n  \n        <div class=\"work-experience\">\n          <ul class=\"work-experience-list\">\n            <li class=\"mb-5 mt-5 text-left text-xl text-white font-semibold\">item 1</li>\n            <li class=\"mb-5 mt-5 text-left text-xl text-white font-semibold\">item 2</li>\n          </ul>\n        </div>\n  \n        <h4 class=\"bold text-4xl text-left tech-experience-title\">Tech</h1>\n        <div class=\"tech-experience\"> \n          <ul class=\"tech-experience-list\">\n            <li class=\"text-left text-xl tech-experience-text font-semibold\">Skill 4</li>\n            <li class=\"text-left text-xl tech-experience-text font-semibold\">Skill 5</li>\n            <li class=\"text-left text-xl tech-experience-text skill-text font-semibold\">Skill 6</li>\n          </ul>\n        </div>\n  \n      </div>\n    </div>\n  </head>\n</html>\n\n";
},"useData":true}